# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build & Lint

on:
  workflow_dispatch:

  pull_request:

  push:
    branches:
      - next
      - main

env:
  NODE_VERSION: lts/*

jobs:
  build-lint-ts:
    name: Build & Lint Typescript
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v4.1.7

      - name: 🏗 Setup nodejs
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 🏗 Setup nodejs corepack
        run: corepack enable

      - name: 🏗 Get yarn config
        id: yarn_config
        run: echo "cache_folder=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: 🏗 Cache Layer
        uses: actions/cache@v4.0.2
        # id: yarn_cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn_config.outputs.cache_folder }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 🏗 Install dependencies
        run: yarn install --immutable

      - name: 🚀 Build Typescript
        run: yarn build

      - name: 🚀 Run ESLint
        run: yarn lint
