# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Dependency Review

on:
  workflow_dispatch:

  pull_request:

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v4.1.7

      - name: 🚀 Dependency Review
        uses: actions/dependency-review-action@v4.3.4
