# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Sync labels

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - next
    paths:
      - .github/labels.yml

jobs:
  labels:
    name: Sync labels
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4.1.4

      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
